---
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: check-xml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: dprint
        name: dprint
        language: system
        entry: dprint fmt
        pass_filenames: false
      - id: trufflehog
        name: trufflehog
        language: system
        entry: trufflehog git file://. --only-verified --fail
        pass_filenames: false
