[settings]
experimental = true

[tools]
delta = "0.19.2"
starship = "1.26.0"
bat = "0.26.1"
prek = "0.5.4"
chezmoi = "2.73.0"
aube = "v2.6.1"
node = "26.10.0"
"aqua:astral-sh/uv" = "0.12.22"
python = "3.14.8"
fzf = "0.74.4"
k9s = "0.51.0"

[settings.ruby]
compile = false
